/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-28 04:05:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FTBC_005fmyView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Edit_005fAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/TopMenuBar_OnlyLogo.jsp", Long.valueOf(1569824019562L));
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/FTBC_Common.jsp", Long.valueOf(1572228384222L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
 
String email = null;
if(session.getAttribute("mem_email")!=null){
email = session.getAttribute("mem_email").toString();
 }
 
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("\t비밀번호 설정페이지\r\n");
      out.write("\t날짜:2019-10-15 정원형 수정\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Edit_Account.css?1\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>   \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("<!--  [iíê·¸]  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- include summernote css/js -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--PG  -->\r\n");
      out.write("\r\n");
      out.write("<!-- ì¬ë¨¸ ë¸í¸ë ì¶©ëë¨\r\n");
      out.write(" <script  src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script> -->\r\n");
      out.write("<!-- iaport : PG(Payment Gateway)_ê²°ì  ëí -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../FTBC_Common/FTBC_Common.css?WJSN\">\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tfont-family : 'SpoqaHanSans,Helvetica Neue,Arial,Helvetica,sans-serif';\r\n");
      out.write("\t}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#email_tbox\").val(\"");
      out.print(email);
      out.write("\");\r\n");
      out.write("})\r\n");
      out.write("function editAccount(){\r\n");
      out.write("\t  $.post(\"/member/editAccount\",$(\"#editAccount_form\").serialize(),function(data){\r\n");
      out.write("\t\t if(data==1){\r\n");
      out.write("\t\t\t alert(\"계정 정보를 변경하였습니다.\");\r\n");
      out.write("\t\t\t location.href=\"/FTBC_myView/Edit_Account.jsp\";\r\n");
      out.write("\t\t }else if(data==2){\r\n");
      out.write("\t\t\t alert(\"변경하실 비밀번호는 기존의 비밀번호로 사용하실 수 없습니다.\");\r\n");
      out.write("\t\t }else if(data==0){\r\n");
      out.write("\t\t\t alert(\"기존 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!--=============================================================================================\r\n");
      out.write("\t로그인 안되있을 경우에 들어갈 상단바\r\n");
      out.write("\t날짜:2019-09-12\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#topMenu_bar{\r\n");
      out.write("\t\tpadding-top:10px;\r\n");
      out.write("\t\theight:55px;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#top_menus a, #top_login a{\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tfont-size:14px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-decoration:none !important;\t\t\r\n");
      out.write("\t\tvertical-align: -webkit-baseline-middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t#topMenu_bar a:hover{\r\n");
      out.write("\t\t color: #8b8b8b;\r\n");
      out.write("\t\t background-size:auto;\r\n");
      out.write("\t\t background-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo{\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tmargin-top:-5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"topMenu_bar\">\r\n");
      out.write("\t<div class=\"col-xs-5 \"></div>\r\n");
      out.write("        <!--===============[ 타이틀 ]==============-->\r\n");
      out.write("      <div class=\"col-xs-2 \">\r\n");
      out.write("         <div id=\"top_title\"  class=\"collapse navbar-collapse\" \">\r\n");
      out.write("            <ul id=\"top_title\" class=\"nav nav-justified\">\r\n");
      out.write("                <li><a href=\"../FTBC_MainView/FTBC_Main.jsp\"><img id=\"logo\" src=\"../FTBC_Images/logo.png\"></a></li>\r\n");
      out.write("            </ul>                \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \t<div class=\"col-xs-5 \"></div>\r\n");
      out.write("       <!--===============[ 로그인 ]==============-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form id=\"editAccount_form\" name=\"editAccount_form\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<!--  상단 부분  -->\r\n");
      out.write("\t<div class=\"row\" id=\"EditAccount_top\">\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t<h2>계정 설정</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\" >\r\n");
      out.write("\t\t\t<div id=\"EditAccount_a\" class=\"EditAccount_a\">\r\n");
      out.write("\t\t\t\t<a href=\"Edit_Profile.jsp\">프로필 설정</a>\r\n");
      out.write("\t\t\t\t<a>계정 설정</a>\r\n");
      out.write("\t\t\t\t<a>지불 정보 설정</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  내용 부분 -->\r\n");
      out.write("\t<div class=\"row\" id=\"EditAccount_content\">\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t\t<div class=\"col-xs-5\"> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!--  이메일 설정  -->\r\n");
      out.write("\t\t\t<div id=\"edit_eamil\" class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\"><label>이메일</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" id=\"email_tbox\" name=\"email_tbox\" readOnly> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--  비밀번호 설정  -->\r\n");
      out.write("\t\t\t<div id=\"edit_pw\" class=\"row edit_ac\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\"><label>비밀번호</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" class=\"edit_txtbox\" placeholder=\"현재 비밀번호\" id=\"pw_tboxpre\" name=\"pw_tboxpre\" style=\"margin-left:0px\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" class=\"edit_txtbox\" placeholder=\"변경할 비밀번호\" id=\"pw_tboxafter\" name=\"pw_tboxafter\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--  수정하기 버튼  -->\r\n");
      out.write("\t\t\t<div id=\"edit_ac_btn\" class=\"row edit_ac\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>&nbsp;</label> </div>\r\n");
      out.write("\t\t\t\t<input type=\"button\"  value=\"수정하기 \" onclick=\"editAccount()\" id=\"edit_ac_button\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-4\">&nbsp;</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
