/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-28 04:05:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FTBC_005fmyView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Edit_005fProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/TopMenuBar_OnlyLogo.jsp", Long.valueOf(1569824019562L));
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/FTBC_Common.jsp", Long.valueOf(1572228384222L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String mem_email = session.getAttribute("mem_email").toString();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("\t프로필 설정페이지\r\n");
      out.write("\t날짜:2019-09-19\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Edit_Profile.css?z1n\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>   \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("<!--  [iíê·¸]  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- include summernote css/js -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--PG  -->\r\n");
      out.write("\r\n");
      out.write("<!-- ì¬ë¨¸ ë¸í¸ë ì¶©ëë¨\r\n");
      out.write(" <script  src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script> -->\r\n");
      out.write("<!-- iaport : PG(Payment Gateway)_ê²°ì  ëí -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../FTBC_Common/FTBC_Common.css?WJSN\">\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tfont-family : 'SpoqaHanSans,Helvetica Neue,Arial,Helvetica,sans-serif';\r\n");
      out.write("\t}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("  <script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- =======[[^^ 고명석 2019-10-16 수정]]======= -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction edit_profile(){\r\n");
      out.write("\t\t $.post(\"/member/MemberUpdate\", $(\".Edit_form\").serialize(), function(data){\r\n");
      out.write("\t\t \t    location.href='/member/memberReplace?mem_email=");
      out.print(mem_email);
      out.write("'; \r\n");
      out.write("\t\t });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getThumbnailPrivew(html) {\r\n");
      out.write("\t    if (html.files && html.files[0]) {\r\n");
      out.write("\t        var reader = new FileReader();\r\n");
      out.write("\t        reader.onload = function (e) {\r\n");
      out.write("\t            $(\"#filebox_img\").css('display', '');\r\n");
      out.write("\t            $(\"#img_box\").html('<img id=\"img_icon\" src=\"' + e.target.result + '\" border=\"0\" alt=\"\" />');\r\n");
      out.write("\t            var pjo_img_result = e.target.result;\r\n");
      out.write("\t            $(\"#edit_img_result\").val(pjo_img_result);\r\n");
      out.write("\t        }\r\n");
      out.write("\t        reader.readAsDataURL(html.files[0]);\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- =======[[^^ 고명석 2019-10-16 수정]]======= -->\r\n");
      out.write("<!-- 내가 만든 프로젝트 페이지는 상단바 바뀌어야함.  -->\r\n");
      out.write("\r\n");
      out.write("  <!--=============================================================================================\r\n");
      out.write("\t로그인 안되있을 경우에 들어갈 상단바\r\n");
      out.write("\t날짜:2019-09-12\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#topMenu_bar{\r\n");
      out.write("\t\tpadding-top:10px;\r\n");
      out.write("\t\theight:55px;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#top_menus a, #top_login a{\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tfont-size:14px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-decoration:none !important;\t\t\r\n");
      out.write("\t\tvertical-align: -webkit-baseline-middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t#topMenu_bar a:hover{\r\n");
      out.write("\t\t color: #8b8b8b;\r\n");
      out.write("\t\t background-size:auto;\r\n");
      out.write("\t\t background-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo{\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tmargin-top:-5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"topMenu_bar\">\r\n");
      out.write("\t<div class=\"col-xs-5 \"></div>\r\n");
      out.write("        <!--===============[ 타이틀 ]==============-->\r\n");
      out.write("      <div class=\"col-xs-2 \">\r\n");
      out.write("         <div id=\"top_title\"  class=\"collapse navbar-collapse\" \">\r\n");
      out.write("            <ul id=\"top_title\" class=\"nav nav-justified\">\r\n");
      out.write("                <li><a href=\"../FTBC_MainView/FTBC_Main.jsp\"><img id=\"logo\" src=\"../FTBC_Images/logo.png\"></a></li>\r\n");
      out.write("            </ul>                \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \t<div class=\"col-xs-5 \"></div>\r\n");
      out.write("       <!--===============[ 로그인 ]==============-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<!--  상단 부분  -->\r\n");
      out.write("\t<div class=\"row\" id=\"EditProfile_top\">\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t<h2>프로필 설정</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\" >\r\n");
      out.write("\t\t\t<div id=\"EditProfile_a\" class=\"EditProfile_a\">\r\n");
      out.write("\t\t\t\t<a>프로필 설정</a>\r\n");
      out.write("\t\t\t\t<a href=\"Edit_Account.jsp\">계정 설정</a>\r\n");
      out.write("\t\t\t\t<a>지불 정보 설정</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  내용 부분 -->\r\n");
      out.write("\t<div class=\"row\" id=\"EditProfile_content\">\r\n");
      out.write("\t<!-- =======[[^^ 고명석 2019-10-16 수정]]======= -->\r\n");
      out.write("\t\t<form class=\"Edit_form\" id=\"Edit_form_profile\" onSubmit=\"return false\" >\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"mem_email\" value=\"");
      out.print(mem_email);
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"edit_img_result\" id=\"edit_img_result\"/>\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t\t<div class=\"col-xs-4\"> \r\n");
      out.write("\t\t\t<!--============[  프로필   사진   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_img\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" id=\"div_pfimg\"><label>프로필 사진</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2\"><div id=\"img_box\"><img id=\"img_icon\" src=\"");
      out.print(session.getAttribute("mem_pfimg").toString());
      out.write("\"></div></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"filebox_img\">\r\n");
      out.write("\t\t\t\t\t \t<div class=\"filebox\">\r\n");
      out.write("\t\t\t\t\t        <input type=\"file\" name=\"cma_file\" id=\"cma_file\" accept=\"image/*\" capture=\"camera\" onchange=\"getThumbnailPrivew(this)\" />\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\"> \r\n");
      out.write("\t\t\t\t\t\t<span id=\"file_exp\">사이즈는 가로 200px, 세로 250px에 최적화 되어 있으며 jpg,gif,png파일을 지원합니다.</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t</div >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--============[  프로필   이름   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_name\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>이름</label></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" id=\"name_tbox\" name=\"name_tbox\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--============[ ^^ 고명석 2019-10-16 수정 ] ==============  -->\r\n");
      out.write("\t\t\t<!--============[  프로필   닉네임   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_name\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>닉네임</label></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" id=\"nick_name\" name=\"mem_nickname\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--============[  프로필   지역   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_loc\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>지역</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"fa edit_txtbox\" id=\"loc_tbox\" name=\"loc_tbox\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--============[  프로필   주소   ]===========-->\r\n");
      out.write("\t\t\t<div class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>주소</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"buyer_addr\" name=\"buyer_addr\" class=\"postcodify_address\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>우편번호</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" size=\"4\" class=\"postcodify_postcode6_1 postcode\" id=\"buyer_post1\" name=\"buyer_post1\"/> &ndash;\r\n");
      out.write("\t\t        <label></label><input type=\"text\" size=\"4\" class=\"postcodify_postcode6_2 postcode\" id=\"buyer_post2\" name=\"buyer_post2\"/> &nbsp;\r\n");
      out.write("\t\t        <button id=\"search_addr\">검색</button>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t    $(\"#search_addr\").postcodifyPopUp();\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!--============[ ^^ 고명석 2019-10-16 수정 ] ==============  -->\r\n");
      out.write("\t\t\t<!--============[  프로필   소개   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_info\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>소개</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" id=\"info_tbox\" name=\"info_tbox\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<p>300자 이내의 자기 소개를 입력해 주세요</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--============[  프로필   웹사이트   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_web\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>웹사이트</label></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" id=\"web_tbox\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<p>웹사이트가 있다면 주소를 입력해주세요.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--============[  프로필   전화번호  ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_phone\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>전화번호</label> </div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" id=\"phone_boxs\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" name=\"hp1\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" name=\"hp2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"edit_txtbox\" name=\"hp3\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<p>전화번호를 입력해 주세요. 밀어주기 및 후원 선물 배송 시 연락을 위해 사용됩니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!--============[  프로필   수정하기 버튼   ]===========-->\r\n");
      out.write("\t\t\t<div id=\"edit_btnd\" class=\"row edit_d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-2 labelbox\" ><label>&nbsp;</label> </div>\r\n");
      out.write("\t\t\t\t<input type=\"button\"  value=\"수정하기  \"  id=\"edit_button\" onClick=\"edit_profile()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t<!--============[  프로필   카드 미리보기    ]===========-->\r\n");
      out.write("\t\t\t<div class=\"card\" id=\"pf_preview\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t<h5>프로필 카드 미리보기</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-4\" >\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"img_preview\" src=\"../FTBC_Images/avatar.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-8\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a><h4 id=\"name_preview\">이름</h4></a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"loc_icon\" src=\"../FTBC_Images/location-pin.png\">\r\n");
      out.write("\t\t\t\t\t\t\t지역정보가 없음\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-footer\">\t\r\n");
      out.write("\t\t\t\t\t<a href=\"FundedProject.jsp\">자세히 보기</a>\t\t\t   \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3\">&nbsp;</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
