/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-29 03:44:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FTBC_005fmyView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Message_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/../FTBC_Common/TopMenuBar.jsp", Long.valueOf(1571276428668L));
    _jspx_dependants.put("/FTBC_myView/./MessageModal.jsp", Long.valueOf(1571637049586L));
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/FTBC_Top.jsp", Long.valueOf(1570767401653L));
    _jspx_dependants.put("/FTBC_myView/./ReAnswer.jsp", Long.valueOf(1571368300803L));
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/FTBC_Common.jsp", Long.valueOf(1572228384222L));
    _jspx_dependants.put("/FTBC_myView/../FTBC_Common/../FTBC_Common/TopMenuBar_Login.jsp", Long.valueOf(1572318799382L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FTBC</title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("\t메세지 페이지 \r\n");
      out.write("\t날짜:2019-09-16\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Message.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>   \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("<!--  [iíê·¸]  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- include summernote css/js -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--PG  -->\r\n");
      out.write("\r\n");
      out.write("<!-- ì¬ë¨¸ ë¸í¸ë ì¶©ëë¨\r\n");
      out.write(" <script  src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script> -->\r\n");
      out.write("<!-- iaport : PG(Payment Gateway)_ê²°ì  ëí -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../FTBC_Common/FTBC_Common.css?WJSN\">\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tfont-family : 'SpoqaHanSans,Helvetica Neue,Arial,Helvetica,sans-serif';\r\n");
      out.write("\t}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("<script src=\"//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js\"\r\n");
      out.write("   type=\"text/javascript\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("a.no-uline { text-decoration:none }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar Sms_code;\r\n");
      out.write("\tvar Smem_email;\r\n");
      out.write("\tvar Spjo_code;\r\n");
      out.write("\tvar Ssend;\r\n");
      out.write("\tvar Squestion;\r\n");
      out.write("\tvar Scontent;\r\n");
      out.write("\tvar Stitle;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Answer(ms_code,mem_email,pjo_code,send,question,content,title){\r\n");
      out.write("\t\tSms_code = ms_code;\r\n");
      out.write("\t\tSmem_email = mem_email;\r\n");
      out.write("\t\tSpjo_code = pjo_code;\r\n");
      out.write("\t\tSsend = send;\r\n");
      out.write("\t\tSquestion = question;\r\n");
      out.write("\t\tScontent = content;\r\n");
      out.write("\t\tStitle = title;\r\n");
      out.write("\t\t$(\"#modal-from\").text(Ssend);\r\n");
      out.write("\t\t$(\"#title\").text(Stitle);\r\n");
      out.write("\t\t$(\"#question\").text(Squestion);\r\n");
      out.write("\t\t$(\"#modal-contents\").text(Scontent);\r\n");
      out.write("\t\t$(\"#message_modal\").modal();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction reAnswer(){\r\n");
      out.write("\t\t$(\"#remodal-from\").text(Ssend);\r\n");
      out.write("\t\t$(\"#retitle\").text(Ssend+\"님에게 답변\");\r\n");
      out.write("\t\t$(\"#rproject_code\").val(Spjo_code);\r\n");
      out.write("\t\t$(\"#rems_code\").val(Sms_code);\r\n");
      out.write("\t\t$(\"#Smem_email\").val(Smem_email);\r\n");
      out.write("\t\t$(\"#requestion\").text(Squestion);\r\n");
      out.write("\t\t$(\"#requestion1\").val(Squestion);\r\n");
      out.write("\t\t$(\"#remodal-contents\").text(\"\");\r\n");
      out.write("\t\t$(\"#remessage_modal\").modal();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction messegeSend(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar select = $(\"#modal-types option:selected\").text();\r\n");
      out.write("\t\t $.post(\"/member/messageSend\", $(\"#remessage_form\").serialize(), function(data){\r\n");
      out.write("\t\t\t \tlocation.href=\"Message.jsp\";\r\n");
      out.write("\t \t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    $(document).on('click', 'a[name=\"allAnTitle\"]', function() {\r\n");
      out.write("\t\tSms_code = table.row($(this).parents('tr:first')).data().ms_code;\r\n");
      out.write("\t\tSpjo_code = table.row($(this).parents('tr:first')).data().project_code;\r\n");
      out.write("\t\tSmem_email = table.row($(this).parents('tr:first')).data().mem_email;\r\n");
      out.write("\t\tSsend = table.row($(this).parents('tr:first')).data().my_nickname;\r\n");
      out.write("\t\tSquestion = table.row($(this).parents('tr:first')).data().ms_question;\r\n");
      out.write("\t\tScontent = table.row($(this).parents('tr:first')).data().ms_content;\r\n");
      out.write("\t\tStitle = table.row($(this).parents('tr:first')).data().ms_title;\r\n");
      out.write("  \t\t$.ajax({\r\n");
      out.write("\t\t\tmethod:'get',\r\n");
      out.write("\t\t\turl:\"/member/messageUpdate?ms_code=\"+Sms_code,\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tAnswer(Sms_code,Smem_email,Spjo_code,Ssend,Squestion,Scontent,Stitle);\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("     });\r\n");
      out.write("    $(document).on('click', 'a[name=\"myAnTitle\"]', function() {\r\n");
      out.write("\t\tSms_code = table2.row($(this).parents('tr:first')).data().ms_code;\r\n");
      out.write("\t\tSpjo_code = table2.row($(this).parents('tr:first')).data().project_code;\r\n");
      out.write("\t\tSmem_email = table2.row($(this).parents('tr:first')).data().mem_email;\r\n");
      out.write("\t\tSsend = table2.row($(this).parents('tr:first')).data().ms_send;\r\n");
      out.write("\t\tSquestion = table2.row($(this).parents('tr:first')).data().ms_question;\r\n");
      out.write("\t\tScontent = table2.row($(this).parents('tr:first')).data().ms_content;\r\n");
      out.write("\t\tStitle = table2.row($(this).parents('tr:first')).data().ms_title;\r\n");
      out.write("  \t\t$.ajax({\r\n");
      out.write("\t\t\tmethod:'get',\r\n");
      out.write("\t\t\turl:\"/member/messageUpdate?ms_code=\"+Sms_code,\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tAnswer(Sms_code,Smem_email,Spjo_code,Ssend,Squestion,Scontent,Stitle);\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("     });\r\n");
      out.write("  \t\r\n");
      out.write("    var table2;\r\n");
      out.write("    var table;\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#uall_btn\").css(\"background-color\", \"gainsboro\");\r\n");
      out.write("\t\t$(\"#uall_btn\").css(\"color\", \"#3A6FF2\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t table = $('#tb_message').DataTable({\r\n");
      out.write("\t            ajax : {\r\n");
      out.write("\t               \"type\" : \"POST\",\r\n");
      out.write("\t               \"url\" : \"/member/getMyMessage?mem_email=");
      out.print(session.getAttribute("mem_email"));
      out.write("\",\r\n");
      out.write("\t               \"dataType\" : \"JSON\"\r\n");
      out.write("\t                  },\r\n");
      out.write("\t            columns : [\r\n");
      out.write("\t                       {data : \"ms_question\", width : 50},\r\n");
      out.write("\t                       {data : \"ms_title\",   width : 180,\r\n");
      out.write("\t                           \"render\": function(data, type, row){\r\n");
      out.write("\t                               if(type=='display'){\r\n");
      out.write("\t                                   data = '<a name=\"allAnTitle\" style=\"text-decoration:none;color:#000000\">' + data+ '</a>';\r\n");
      out.write("\t                               }\r\n");
      out.write("\t                               return data;\r\n");
      out.write("\t                           }},\r\n");
      out.write("\t                       {data : \"my_nickname\", width : 50},\r\n");
      out.write("\t                       {data : \"rec_nickname\", width : 50},\r\n");
      out.write("\t                       {data : \"ms_date\", width : 50}, \r\n");
      out.write("\t                       {data : \"ms_isread\", width : 50,\r\n");
      out.write("\t                    \t   \"render\": function(data, type, row){\r\n");
      out.write("\t                               if(type=='display'){\r\n");
      out.write("\t                            \t   if(data==1){\r\n");
      out.write("\t                                   data = \"읽음\";\r\n");
      out.write("\t                            \t   }else{\r\n");
      out.write("\t                            \t\tdata = \"안읽음\"   \r\n");
      out.write("\t                            \t   }\r\n");
      out.write("\t                               }\r\n");
      out.write("\t                               return data;\r\n");
      out.write("\t                    \t   }\r\n");
      out.write("\t                       }, \r\n");
      out.write("\t                       {data : \"ms_code\", visible : false},\r\n");
      out.write("\t                       {data : \"mem_email\", visible: false},\r\n");
      out.write("\t                       {data : \"ms_content\", visible: false},\r\n");
      out.write("\t                       {data : \"project_code\", visible: false}\r\n");
      out.write("\t                       ],\r\n");
      out.write("\t              language: {\r\n");
      out.write("\t                  \"emptyTable\": \"메세지가 존재하지 않습니다\",\r\n");
      out.write("\t                  \"lengthMenu\": \"페이지당 _MENU_ 개씩 보기\",\r\n");
      out.write("\t                  \"info\": \"현재 _START_ - _END_ / _TOTAL_건\",\r\n");
      out.write("\t                  \"infoEmpty\": \"메세지가 존재하지 않습니다\",\r\n");
      out.write("\t                  \"infoFiltered\": \"( _MAX_건의 데이터에서 필터링됨 )\",\r\n");
      out.write("\t                  \"search\": \"&nbsp;&nbsp;&nbsp;검색 : \",\r\n");
      out.write("\t                  \"zeroRecords\": \"일치하는 데이터가 없어요.\",\r\n");
      out.write("\t                  \"loadingRecords\": \"로딩중...\",\r\n");
      out.write("\t                  \"processing\":     \"잠시만 기다려 주세요...\",\r\n");
      out.write("\t                  \"paginate\": {\r\n");
      out.write("\t                      \"next\": \"다음\",\r\n");
      out.write("\t                      \"previous\": \"이전\"\r\n");
      out.write("\t                  }\r\n");
      out.write("\t              }\r\n");
      out.write("\t         });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t table2 = $('#tb_PjoMessage').DataTable({\r\n");
      out.write("\t            ajax : {\r\n");
      out.write("\t               \"type\" : \"POST\",\r\n");
      out.write("\t               \"url\" : \"/member/myPjoMessage?mem_email=");
      out.print(session.getAttribute("mem_email"));
      out.write("\",\r\n");
      out.write("\t               \"dataType\" : \"JSON\"\r\n");
      out.write("\t                  },\r\n");
      out.write("\t            columns : [\r\n");
      out.write("\t                       {data : \"ms_question\", width : 50},\r\n");
      out.write("\t                       {data : \"ms_title\",   width : 180,\r\n");
      out.write("\t                           \"render\": function(data, type, row){\r\n");
      out.write("\t                               if(type=='display'){\r\n");
      out.write("\t                                   data = '<a name=\"myAnTitle\" style=\"text-decoration:none;color:#000000\">' + data+ '</a>';\r\n");
      out.write("\t                               }\r\n");
      out.write("\t                               return data;\r\n");
      out.write("\t                           }},\r\n");
      out.write("\t                       {data : \"my_nickname\", width : 50},\r\n");
      out.write("\t                       {data : \"rec_nickname\", width : 50},\r\n");
      out.write("\t                       {data : \"ms_date\", width : 50}, \r\n");
      out.write("\t                       {data : \"ms_isread\", width : 50,\r\n");
      out.write("\t                    \t   \"render\": function(data, type, row){\r\n");
      out.write("\t                               if(type=='display'){\r\n");
      out.write("\t                            \t   if(data==1){\r\n");
      out.write("\t                                   data = \"읽음\";\r\n");
      out.write("\t                            \t   }else{\r\n");
      out.write("\t                            \t\tdata = \"안읽음\"   \r\n");
      out.write("\t                            \t   }\r\n");
      out.write("\t                               }\r\n");
      out.write("\t                               return data;\r\n");
      out.write("\t                    \t   }}, \r\n");
      out.write("\t                       {data : \"ms_code\", visible : false},\r\n");
      out.write("\t                       {data : \"mem_email\", visible: false},\r\n");
      out.write("\t                       {data : \"ms_content\", visible: false},\r\n");
      out.write("\t                       {data : \"project_code\", visible: false}\r\n");
      out.write("\t                       ],\r\n");
      out.write("\t              language: {\r\n");
      out.write("\t                  \"emptyTable\": \"메세지가 존재하지 않습니다\",\r\n");
      out.write("\t                  \"lengthMenu\": \"페이지당 _MENU_ 개씩 보기\",\r\n");
      out.write("\t                  \"info\": \"현재 _START_ - _END_ / _TOTAL_건\",\r\n");
      out.write("\t                  \"infoEmpty\": \"메세지가 존재하지 않습니다\",\r\n");
      out.write("\t                  \"infoFiltered\": \"( _MAX_건의 데이터에서 필터링됨 )\",\r\n");
      out.write("\t                  \"search\": \"&nbsp;&nbsp;&nbsp;검색 : \",\r\n");
      out.write("\t                  \"zeroRecords\": \"일치하는 데이터가 없어요.\",\r\n");
      out.write("\t                  \"loadingRecords\": \"로딩중...\",\r\n");
      out.write("\t                  \"processing\":     \"잠시만 기다려 주세요...\",\r\n");
      out.write("\t                  \"paginate\": {\r\n");
      out.write("\t                      \"next\": \"다음\",\r\n");
      out.write("\t                      \"previous\": \"이전\"\r\n");
      out.write("\t                  }\r\n");
      out.write("\t              }\r\n");
      out.write("\t         });\r\n");
      out.write("          $('#tb_message_filter').prepend('<select id=\"select\"></select>');\r\n");
      out.write("          $('#tb_message > thead > tr').children().each(function (indexInArray, valueOfElement) { \r\n");
      out.write("             if(indexInArray != 4) {\r\n");
      out.write("                 $('#select').append('<option>'+valueOfElement.innerHTML+'</option>');\r\n");
      out.write("             }\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("          $('.dataTables_filter input').unbind().bind('keyup', function () {\r\n");
      out.write("              var colIndex = document.querySelector('#select').selectedIndex;\r\n");
      out.write("              table.column(colIndex).search(this.value).draw();\r\n");
      out.write("          });\r\n");
      out.write("          $('#tb_PjoMessage_filter').prepend('<select id=\"select1\"></select>');\r\n");
      out.write("          $('#tb_PjoMessage > thead > tr').children().each(function (indexInArray, valueOfElement) { \r\n");
      out.write("             if(indexInArray != 4) {\r\n");
      out.write("                 $('#select1').append('<option>'+valueOfElement.innerHTML+'</option>');\r\n");
      out.write("             }\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("\t});\r\n");
      out.write("   function hide1(){\r\n");
      out.write("\t   $(\"#my_project\").hide();\r\n");
      out.write("\t   $(\"#ur_project\").show();\r\n");
      out.write("   }\r\n");
      out.write("   function hide2(){\r\n");
      out.write("\t   $(\"#ur_project\").hide();\r\n");
      out.write("\t   $(\"#my_project\").show();\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!----------------상단바------------>\r\n");
      out.write('\r');
      out.write('\n');

	if(session.getAttribute("mem_email") != null) {

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

   String mem_email = session.getAttribute("mem_email").toString();
   String mem_pfimg = session.getAttribute("mem_pfimg").toString();
   String mem_name = session.getAttribute("mem_name").toString();
   String mem_isauthority = session.getAttribute("mem_isAuthority").toString();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FTBC</title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("   로그인 되있을 경우에 들어갈 상단바\r\n");
      out.write("   로그인 부분이 회원이름으로.\r\n");
      out.write("   날짜:2019-09-12\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write(".FTBC_loginbar {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenuBar_bar {\r\n");
      out.write("\theight: 65px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenuBar_menus a, #top_login a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tline-height: 20px !important;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttext-decoration: none !important;\r\n");
      out.write("\tvertical-align: -webkit-baseline-middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenuBar_bar a:hover {\r\n");
      out.write("\tcolor: #8b8b8b;\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenuBar_menus {\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#TopMenuBar_Login_mem_pfimg {\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenuBar_FTBClogo {\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin-top: -5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"topMenuBar_bar\">\r\n");
      out.write("\t\t<div class=\"col-xs-2 \"></div>\r\n");
      out.write("\t\t<!--===============[ 메뉴 ] =============-->\r\n");
      out.write("\t\t<div class=\"col-xs-2 FTBC_loginbar\">\r\n");
      out.write("\t\t\t<div class=\"dropdown\" id=\"topMenuBar_menus\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-list\"></i>프로젝트 <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"about-us\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../FTBC_LookView/LookAround_Project.jsp\">프로젝트\r\n");
      out.write("\t\t\t\t\t\t\t둘러보기 </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../FTBC_CreateView/CreatProject_Terms.jsp\">프로젝트\r\n");
      out.write("\t\t\t\t\t\t\t올리기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../FTBC_BlockChainView/BlockChain_Main2.jsp\">프로젝트\r\n");
      out.write("\t\t\t\t\t\t\t블록체인</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-1 \"></div>\r\n");
      out.write("\t\t<!--===============[ 타이틀 ]==============-->\r\n");
      out.write("\t\t<div class=\"col-xs-2 FTBC_loginbar\">\r\n");
      out.write("\t\t\t<div id=\"topMenuBar_title\" class=\"collapse navbar-collapse\"\">\r\n");
      out.write("\t\t\t\t<ul id=\"topMenuBar_title\" class=\"nav nav-justified\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../FTBC_MainView/FTBC_Main.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\t\tid=\"topMenuBar_FTBClogo\" src=\"../FTBC_Images/logo.png\"></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-1 \"></div>\r\n");
      out.write("\t\t<!--===============[ 로그인 ]==============-->\r\n");
      out.write("\t\t<div class=\"col-xs-3 FTBC_loginbar\">\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<ul id=\"top_login\" class=\"nav nav-justified\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/FTBC_myView/myPage.jsp\" id=\"mem_name\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"padding: 10px 0 0 0;\"> <i class=\"fa fa-search\"></i> ");
      out.print(mem_name );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.print(mem_pfimg );
      out.write("\" id=\"TopMenuBar_Login_mem_pfimg\"></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

	}
	else {

      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("  <!--=============================================================================================\r\n");
      out.write("\t로그인 안되있을 경우에 들어갈 상단바\r\n");
      out.write("\t날짜:2019-09-12\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#topMenuBar_bar{\r\n");
      out.write("\t\tpadding-top:10px;\r\n");
      out.write("\t\theight:55px;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#topMenuBar_menus a, #top_login a{\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tfont-size:14px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-decoration:none !important;\t\t\r\n");
      out.write("\t\tvertical-align: -webkit-baseline-middle;\r\n");
      out.write("\t}\r\n");
      out.write("\t#topMenuBar_bar a:hover{\r\n");
      out.write("\t\t color: #8b8b8b;\r\n");
      out.write("\t\t background-size:auto;\r\n");
      out.write("\t\t background-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#topMenuBar_menus{\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fa-bars{\r\n");
      out.write("\t\tmargin-right:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#topMenuBar_FTBClogo{\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tmargin-top:-5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction topLogin() {\r\n");
      out.write("\t\tvar url = window.location.href;\r\n");
      out.write("\t\tconsole.log(\"url : \"+url);\r\n");
      out.write("\t\tlocation.href=\"../FTBC_MainView/FTBC_LoginLayout.jsp?preURL=\"+url;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"topMenuBar_bar\">\r\n");
      out.write("\t<div class=\"col-xs-2 \"></div>\r\n");
      out.write("\t   <!--===============[ 메뉴 ] =============-->\r\n");
      out.write("    <div class=\"col-xs-2 \">\r\n");
      out.write("\t\t<div class=\"dropdown\" id=\"topMenuBar_menus\">\t\t\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-bars\"></i>프로젝트 <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"about-us\">\r\n");
      out.write("\t\t\t<li><a href=\"../FTBC_LookView/LookAround_Project.jsp\">프로젝트 둘러보기 </a></li>\r\n");
      out.write("              <li><a href=\"../FTBC_CreateView/CreatProject_Terms.jsp\">프로젝트 올리기</a></li>\r\n");
      out.write("              <li><a href=\"../FTBC_BlockChainView/BlockChain_Main2.jsp\">프로젝트 블록체인</a></li>  \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \t<div class=\"col-xs-1 \"></div>\r\n");
      out.write("        <!--===============[ 타이틀 ]==============-->\r\n");
      out.write("      <div class=\"col-xs-2 \">\r\n");
      out.write("         <div id=\"topMenuBar_title\"  class=\"collapse navbar-collapse\" \">\r\n");
      out.write("            <ul id=\"topMenuBar_title\" class=\"nav nav-justified\">\r\n");
      out.write("                <li><a href=\"../FTBC_MainView/FTBC_Main.jsp\"><img id=\"topMenuBar_FTBClogo\" src=\"../FTBC_Images/logo.png\"></a></li>\r\n");
      out.write("            </ul>                \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \t<div class=\"col-xs-1 \"></div>\r\n");
      out.write("       <!--===============[ 로그인 ]==============-->\r\n");
      out.write("      <div class=\"col-xs-3 \">\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" \">\r\n");
      out.write("           <ul id=\"top_login\" class=\"nav nav-justified\">\r\n");
      out.write("              <li><a href=\"javascript: topLogin()\" id=\"topLogin\">로그인</a></li>\r\n");
      out.write("            </ul>                \r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("</div>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
 
	}

      out.write('	');
      out.write('	');
      out.write("\r\n");
      out.write("<hr class=\"FTBC_hr\" >\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<!--상단 배너 부분 -->\r\n");
      out.write("\t<div class=\"row\"  id=\"MessageBanner\" >\r\n");
      out.write("\t\t<div class=\"col-xs-3 banner_side\"></div>\r\n");
      out.write("\t\t<div class=\"col-xs-7\">\r\n");
      out.write("\t\t<div id=\"floater\">&nbsp;</div>\r\n");
      out.write("\t\t<div class=\"row\"  id=\"msgBanner_top\">\r\n");
      out.write("\t\t\t<img src=\"../FTBC_Images/messageicondark.png\" id=\"msg_dark\">\r\n");
      out.write("\t\t\t<span id=\"msg_title\">메시지</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"nav nav-tabs\" id=\"#msgBanner_tab\">\r\n");
      out.write("\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t<a class=\"tab_menu\" data-toggle=\"tab\" href=\"#ur_project\" onclick=\"hide1()\">문의/후원 프로젝트</a></li>\r\n");
      out.write("\t\t\t<li><a class=\"tab_menu\" data-toggle=\"tab\" href=\"#my_project\" onclick=\"hide2()\">만든 프로젝트</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-2 banner_side\"></div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"ur_project\" class=\"tab-pane fade in active\">\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"margin-bottom: 50px;\"></div>\r\n");
      out.write("\t    \t<div class=\"row\" id=\"blockChain_List\">\r\n");
      out.write("\t         <div id=\"Block_left\" class=\"col-sm-2\">&nbsp;</div>\r\n");
      out.write("\t         <div id=\"Blcok_Center\" class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<table id=\"tb_message\" class=\"table table-striped table-bordered\"\r\n");
      out.write("\t               style=\"width: 100%;\">\r\n");
      out.write("\t               <thead>\r\n");
      out.write("\t                  <tr>\r\n");
      out.write("\t          \t\t\t<th>문의유형</th>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>보낸이</th>\r\n");
      out.write("\t\t\t\t\t\t<th>받는이</th>\r\n");
      out.write("\t\t\t\t\t\t<th>날짜</th>\r\n");
      out.write("\t\t\t\t\t\t<th>읽음</th>\r\n");
      out.write("\t                  </tr>\r\n");
      out.write("\t               </thead>\r\n");
      out.write("\t            </table>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t         <div id=\"Block_Right\" class=\"col-sm-2\">&nbsp;</div>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"my_project\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"margin-bottom: 50px;\"></div>\r\n");
      out.write("\t    \t<div class=\"row\" id=\"blockChain_List\">\r\n");
      out.write("\t         <div id=\"Block_left\" class=\"col-sm-2\">&nbsp;</div>\r\n");
      out.write("\t         <div id=\"Blcok_Center\" class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<table id=\"tb_PjoMessage\" class=\"table table-striped table-bordered\"\r\n");
      out.write("\t               style=\"width: 100%;\">\r\n");
      out.write("\t               <thead>\r\n");
      out.write("\t                  <tr>\r\n");
      out.write("\t          \t\t\t<th>문의유형</th>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>보낸이</th>\r\n");
      out.write("\t\t\t\t\t\t<th>받는이</th>\r\n");
      out.write("\t\t\t\t\t\t<th>날짜</th>\r\n");
      out.write("\t\t\t\t\t\t<th>읽음</th>\r\n");
      out.write("\t                  </tr>\r\n");
      out.write("\t               </thead>\r\n");
      out.write("\t            </table>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t         <div id=\"Block_Right\" class=\"col-sm-2\">&nbsp;</div>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"message_modal\" role=\"dialog\">\r\n");
      out.write("\t\t<div id=\"modal-dialog\" class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div id=\"modal-header\" class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<label id=\"title\">카테고리 </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"modal-body\" class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"modal-to\">보낸 사람 : </label>\r\n");
      out.write("\t\t\t\t\t\t<!-- #DB -->\r\n");
      out.write("\t\t\t\t\t\t<label id=\"modal-from\">[test1234]님</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"Divider\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- #form태그 -->\r\n");
      out.write("\t\t\t\t\t<form id=\"message_form\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- #DB -->\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"qustion_sel\">문의유형 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"question\">카테고리 </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"Divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"modal-contents\" class=\"form-control\" disabled \r\n");
      out.write("\t\t\t\t\t\t\t\toninput=\"javascript:test(this)\" name=\"modal-contents\" rows=\"8\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"footer-cancle\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-ban\" style=\"margin-right: 5px\"></i>닫기\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"footer-submit\" type=\"button\" class=\"btn btn-default\" onClick=\"reAnswer()\" \r\n");
      out.write("\t\t\t\t\t data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-envelope\" style=\"margin-right: 5px\"></i>답변\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"remessage_modal\" role=\"dialog\">\r\n");
      out.write("\t\t<div id=\"modal-dialog\" class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div id=\"modal-header\" class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<label id=\"retitle\">카테고리 </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"modal-body\" class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"modal-to\">받는 사람 : </label>\r\n");
      out.write("\t\t\t\t\t\t<!-- #DB -->\r\n");
      out.write("\t\t\t\t\t\t<label id=\"remodal-from\">[test1234]님</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"Divider\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- #form태그 -->\r\n");
      out.write("\t\t\t\t\t<form id=\"remessage_form\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"rems_code\" name=\"ms_code\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"rproject_code\" name=\"PROJECT_CODE\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"resend_mem\" name=\"send_mem\" value=\"");
      out.print(session.getAttribute("mem_email"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"Smem_email\" name=\"mem_email\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"requestion1\" name=\"modal-types_select\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- #DB -->\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"qustion_sel\">문의유형 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"requestion\">카테고리 </label>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"modal-to\">&nbsp;&nbsp;&nbsp;제목 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" style=\"width:200px;border-radius:5px;background-color: #ffffff;\" name=\"MS_TITLE\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"Divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"remodal-contents\" class=\"form-control\"  \r\n");
      out.write("\t\t\t\t\t\t\t\toninput=\"javascript:test(this)\" name=\"modal-contents\" rows=\"8\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"footer-cancle\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-ban\" style=\"margin-right: 5px\"></i>닫기\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"footer-submit\" type=\"button\" class=\"btn btn-default\" onClick=\"messegeSend()\" \r\n");
      out.write("\t\t\t\t\t data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-envelope\" style=\"margin-right: 5px\"></i>답변\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
      out.write("\t \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
