/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-11 00:51:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FTBC_005fCreateView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Project_005fStoryTelling_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>프로젝트 만들기 </title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("\t프로젝트 올리기 -스토리텔링 탭\r\n");
      out.write("\t날짜:2019-09-12\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Project_StoryTelling.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t//스토리 입력하기 \r\n");
      out.write("\t\tfunction enterStory() {\r\n");
      out.write("\t\t\t$(\"#st_story1\").hide();\r\n");
      out.write("\t\t\t$(\"#st_story2\").show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//스토리 입력 취소\r\n");
      out.write("\t\tfunction storyCancel() {\r\n");
      out.write("\t\t\t$(\"#st_story2\").hide();\r\n");
      out.write("\t\t\t$(\"#st_story1\").show();\r\n");
      out.write("\t\t\tvar story2_txt =  $('#summernote').summernote('code');\r\n");
      out.write("\t\t\tconsole.log(\"story2_txt\" + story2_txt); \r\n");
      out.write("\t\t\tif(story2_txt != \"<p><br></p>\"){\r\n");
      out.write("\t\t\t\t$(\"#story_content\").html(story2_txt);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tstory_change();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//스토리 저장\r\n");
      out.write("\t\tfunction storySave() {\r\n");
      out.write("\t\t\tvar story2_txt =  $('#summernote').summernote('code');\r\n");
      out.write("\t\t\tconsole.log(\"story2_txt\" + story2_txt); \r\n");
      out.write("\t\t\talert(story2_txt);\r\n");
      out.write("\t\t\tif(story2_txt != \"<p><br></p>\"){\r\n");
      out.write("\t\t\t\t$(\"#st_story1\").html(story2_txt);\r\n");
      out.write("\t\t\t\tstory_change();\r\n");
      out.write("\t\t\t\tstoryCancel();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\talert(\"스토리를 입력해 주세요\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#st_story2\").hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction story_change(){\r\n");
      out.write("\t\t\tvar story2_txt =  $('#summernote').summernote('code');\r\n");
      out.write("\t\t\tif(story2_txt == \"<p><br></p>\"){\r\n");
      out.write("\t\t\t\t$(\"#check_tab3\").html('<img id=\"check_tab3\" src=\"../FTBC_Images/check1.png\">');\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\t$(\"#check_tab3\").html('<img id=\"check_tab3\" src=\"../FTBC_Images/check.png\">');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction story_check_count(){\r\n");
      out.write("\t\t\tvar story2_txt =  $('#summernote').summernote('code');\r\n");
      out.write("\t\t\tif(story2_txt == \"<p><br></p>\"){\r\n");
      out.write("\t\t\t\tcheck = check+\",스토리텔링\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#check_tab3\").html('<img id=\"check_tab3\" src=\"../FTBC_Images/check.png\">');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div>\r\n");
      out.write("\t<p>프로젝트 스토리</p>\r\n");
      out.write("\t<div id=\"st_story1\" onclick=\"enterStory()\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<label>&nbsp; 프로젝트 스토리</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\" id=\"story_content\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<img src=\"../FTBC_Images/finger.png\"></img><label>&nbsp; 프로젝트\t스토리를 입력해주세요</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<img src=\"../FTBC_Images/edit.png\"></img><label>&nbsp; 입력하기</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end of st_story1  -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"st_story2\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<label id=\"story2_title\">프로젝트 스토리</label>\r\n");
      out.write("\t\t\t\t<p id=\"story2_guide\">\r\n");
      out.write("\t\t\t\t\t<a id=\"story2_guide_a\">[프로젝트 스토리는 어떻게 작성해야 하나요?]</a>를 읽어보시고 스토리텔링에 필요한 요소들을 확인하여\r\n");
      out.write("\t\t\t\t\t작성해주세요.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div id=\"editor\">\r\n");
      out.write("\t\t\t\t<form id=\"f_summer\" method=\"post\" class=\"create_form\" onSubmit=\"return false\">\r\n");
      out.write("\t\t\t\t\t<textarea id=\"summernote\" name=\"editordata\"></textarea>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$('#summernote').summernote({\r\n");
      out.write("\t\t\t\t\t\tplaceholder : 'Hello bootstrap 4',\r\n");
      out.write("\t\t\t\t\t\ttabsize : 2,\r\n");
      out.write("\t\t\t\t\t\theight : 400,\r\n");
      out.write("\t\t\t\t\t\tlang : 'ko-KR' // default: 'en-US'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end of editor  -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<input id=\"story_cancel\" type=\"button\" onClick=\"storyCancel()\"\tvalue=\"취소하기\">\r\n");
      out.write("\t\t\t<input id=\"story_save\" type=\"button\" onClick=\"storySave()\" value=\"저장하기\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end of st_story2  -->\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
