/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-11 00:48:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FTBC_005fCreateView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Project_005fAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>프로젝트 만들기 </title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("\t프로젝트 올리기 - 계좌 설정 탭\r\n");
      out.write("\t날짜:2019-09-12\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Project_Account.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t/******* 본인인증  *****/\r\n");
      out.write("\tfunction enterpnum() {\r\n");
      out.write("\t\t$(\"#ac_urself1\").hide();\r\n");
      out.write("\t\t$(\"#ac_urself2\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cancelSelf() {\r\n");
      out.write("\t\t$(\"#ac_urself2\").hide();\r\n");
      out.write("\t\t$(\"#ac_urself1\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/******* 입금계좌  *****/\r\n");
      out.write("\tfunction enterAccount() {\r\n");
      out.write("\t\t$(\"#ac_account1\").hide();\r\n");
      out.write("\t\t$(\"#ac_account2\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cancelAccount() {\r\n");
      out.write("\t\t$(\"#ac_account2\").hide();\r\n");
      out.write("\t\t$(\"#ac_account1\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveAccount() {\r\n");
      out.write("\t\t\tvar account2_textbox = $(\"#account2_textbox\").val( );\r\n");
      out.write("\t\t\tvar Account_form = document.Account_form;\r\n");
      out.write("\t\t\tif(Account_form.account2_textbox.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"계좌번호를 입력해 주세요\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\taccount_change();\r\n");
      out.write("\t\t\t\tcancelAccount();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\"#ac_email2\").hide();\r\n");
      out.write("\t\t$(\"#ac_urself2\").hide();\r\n");
      out.write("\t\t$(\"#ac_account2\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction account_change(){\r\n");
      out.write("\t\tvar Account_form = document.Account_form;\r\n");
      out.write("\t\tif(Account_form.account2_textbox.value==\"\"||$(\"#account2_select\").val()==null\r\n");
      out.write("\t\t){\r\n");
      out.write("\t\t\t$(\"#check_tab4\").html('<img id=\"check_tab4\" src=\"../FTBC_Images/check1.png\">');\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\t$(\"#check_tab4\").html('<img id=\"check_tab4\" src=\"../FTBC_Images/check.png\">');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction account_check_count(){\r\n");
      out.write("\t\tvar Account_form = document.Account_form;\r\n");
      out.write("\t\tif(Account_form.account2_textbox.value==\"\"){\r\n");
      out.write("\t\t\tcheck = check+\",계좌번호\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$(\"#check_tab4\").html('<img id=\"check_tab4\" src=\"../FTBC_Images/check.png\">');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<form id=\"Account_form\" name=\"Account_form\" onSubmit=\"return false\" class=\"create_form\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--==================================[ 보닌 인증  ]============================  -->\r\n");
      out.write("\t<p>본인 인증</p>\r\n");
      out.write("\t<div id=\"ac_urself1\" onclick=\"enterpnum()\">\r\n");
      out.write("\t\t\t<div class=\"row\" id=\"ac_urself1_content\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../FTBC_Images/finger.png\"></img><label class=\"account_label\">&nbsp; 본인 인증을 진행해 주세요</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../FTBC_Images/edit.png\"></img><label class=\"account_label\">&nbsp; 수정하기</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--end of ac_urself1  -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"ac_urself2\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label class=\"account_label\">&nbsp; 휴대폰 번호로 한국모바일인증(주)의 본인확인서비스를 통해 본인 인증을 진행합니다. </label>\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t<div id=\"urself2_btns\">\r\n");
      out.write("\t\t\t\t<input id=\"selfverify_cancel\" type=\"button\" onClick=\"cancelSelf()\"value=\"취소하기\"> \r\n");
      out.write("\t\t\t\t<input id=\"selfverify_verify\" type=\"button\" onClick=\"verifySelf()\" value=\"인증받기\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--==================================[ 입금 계좌 ]============================  -->\r\n");
      out.write("\t<p>입금 계좌</p>\r\n");
      out.write("\t<div id=\"ac_account1\" onclick=\"enterAccount()\">\r\n");
      out.write("\t\t<div class=\"row\" id=\"ac_account1_content\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<img src=\"../FTBC_Images/finger.png\"></img><label class=\"account_label\">&nbsp; 본인 인증을 진행해 주세요</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<img src=\"../FTBC_Images/edit.png\"></img><label class=\"account_label\">&nbsp; 수정하기</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!--end of ac_account1  -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"ac_account2\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label>&nbsp; 계좌 번호 </label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label>&nbsp; 펀딩에 성공할시 입금 받으실 계좌를 입력해 주세요.</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ac_account2_content\">\r\n");
      out.write("\t\t\t\t\t<select id=\"account2_select\">\r\n");
      out.write("\t\t\t\t\t\t<option>현대카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>삼성카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Kb국민</option>\r\n");
      out.write("\t\t\t\t\t\t<option>비씨카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>신한카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>하나카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>롯데카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>NH농협</option>\r\n");
      out.write("\t\t\t\t\t\t<option>씨티카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>전북카드</option>\r\n");
      out.write("\t\t\t\t\t\t<option>경남카드</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"account2_textbox\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"account2_btns\">\r\n");
      out.write("\t\t\t\t<input id=\"account_cancel\" type=\"button\" onClick=\"cancelAccount()\"value=\"취소하기\"> \r\n");
      out.write("\t\t\t\t<input id=\"account_verify\" type=\"button\" onClick=\"saveAccount()\" value=\"저장하기\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
